In [1]:
import os
import json
import numpy as np
import pandas as pd

Group json

In [2]:
def read_json_files(folder_path):
    json_data = []
    
    for filename in os.listdir(folder_path):
        if filename.endswith(".json"):
            file_path = os.path.join(folder_path, filename)
            with open(file_path, "r") as file:
                for line in file:
                    try:
                        line_data = json.loads(line)
                        json_data.append(line_data)
                    except json.JSONDecodeError:
                        print(f"Error parsing JSON line: {line}")
    
    return json_data

In [3]:
file_path = "Videos"
json_data = read_json_files(file_path)

In [4]:
full_body = []
half_body = []

In [5]:
for item in json_data:
    predictions = item["predictions"]
    for prediction in predictions:
        keypoints = prediction["keypoints"]
        bbox = prediction["bbox"]
        score = prediction["score"]
        category_id = prediction["category_id"]

        keypoints_arr = np.array(keypoints).reshape(-1, 3)  # Reshape keypoints as (n, 3) array
        c_values = keypoints_arr[:, 2]  # Extract all c values

        if np.any(c_values <= 0):
            if not np.all(c_values<=0):
                keypoints_without_c = keypoints_arr[:, :2]  # Remove c values
                half_body.append(keypoints_without_c.tolist())
        else:
            keypoints_without_c = keypoints_arr[:, :2]  # Remove c values
            full_body.append(keypoints_without_c.tolist())

In [6]:
COCO_Person_Keypoints = [
    "nose", "left_eye", "right_eye", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"
]

In [7]:
COCO_Person_Keypoints_XY = []

for item in COCO_Person_Keypoints:
    COCO_Person_Keypoints_XY.append(item + "_x")
    COCO_Person_Keypoints_XY.append(item + "_y")

In [9]:
half_body = np.array(half_body)
full_body = np.array(full_body)

In [10]:
reshape_half_body = half_body.reshape(-1,34)
reshape_full_body = full_body.reshape(-1,34)

In [11]:
df_full_body = pd.DataFrame(reshape_full_body, columns=COCO_Person_Keypoints_XY)
df_half_body = pd.DataFrame(reshape_half_body, columns=COCO_Person_Keypoints_XY)

In [12]:
df_half_body

,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,right_ear_y,...,right_hip_x,right_hip_y,left_knee_x,left_knee_y,right_knee_x,right_knee_y,left_ankle_x,left_ankle_y,right_ankle_x,right_ankle_y
0,828.04,154.90,836.28,138.73,0.00,0.00,873.73,132.16,0.00,0.00,...,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,823.20,152.88,830.07,135.78,0.00,0.00,865.68,130.07,0.00,0.00,...,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,818.41,152.27,824.43,133.69,0.00,0.00,861.40,127.13,0.00,0.00,...,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,812.72,150.57,819.47,131.78,0.00,0.00,858.62,124.80,0.00,0.00,...,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,805.06,150.37,812.18,130.86,0.00,0.00,851.60,125.38,0.00,0.00,...,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583390,174.96,232.17,176.34,229.72,172.92,230.08,180.00,230.50,170.95,231.55,...,172.71,273.07,0.0,-4.0,0.0,-4.0,0.0,-4.0,0.0,-4.0
583391,227.10,257.88,228.04,255.09,224.66,255.99,0.00,-4.00,221.04,257.27,...,0.00,-4.00,0.0,-4.0,0.0,-4.0,0.0,-4.0,0.0,-4.0
583392,270.16,253.67,272.09,251.12,268.03,251.29,276.38,251.94,264.76,252.77,...,266.84,304.41,0.0,-4.0,0.0,-4.0,0.0,-4.0,0.0,-4.0
583393,0.00,-4.00,0.00,-4.00,0.00,-4.00,0.00,-4.00,336.29,241.88,...,333.16,284.75,0.0,-4.0,0.0,-4.0,0.0,-4.0,0.0,-4.0
583394,0.00,-4.00,0.00,-4.00,0.00,-4.00,0.00,-4.00,0.00,-4.00,...,34.16,322.48,0.0,-4.0,0.0,-4.0,0.0,-4.0,0.0,-4.0

In [13]:
df_full_body

,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,right_ear_y,...,right_hip_x,right_hip_y,left_knee_x,left_knee_y,right_knee_x,right_knee_y,left_ankle_x,left_ankle_y,right_ankle_x,right_ankle_y
0,670.79,278.54,672.53,276.80,669.33,276.84,675.25,277.91,667.14,277.75,...,663.08,311.66,671.87,333.78,661.95,333.37,669.33,353.90,658.41,353.79
1,670.59,278.36,672.35,276.72,669.16,276.74,675.20,277.91,667.10,277.68,...,663.10,311.44,671.51,333.73,661.97,333.11,669.15,353.84,658.44,353.46
2,670.50,278.39,672.29,276.75,669.06,276.78,675.09,277.89,666.95,277.59,...,663.07,311.42,671.51,333.85,661.94,333.21,669.08,353.98,658.33,353.18
3,670.49,278.43,672.24,276.77,668.98,276.81,675.09,277.92,666.81,277.74,...,663.03,311.28,671.26,333.48,661.58,331.99,668.91,353.41,658.26,352.93
4,670.54,278.39,672.16,276.70,668.93,276.77,674.87,277.80,666.57,277.89,...,662.88,311.34,671.12,333.49,661.34,331.94,669.10,353.39,658.04,352.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26464,461.05,53.93,463.20,51.32,458.48,51.65,466.68,53.76,455.18,54.67,...,456.13,108.14,475.97,143.02,451.48,145.44,482.53,174.69,448.06,176.54
26465,461.10,53.88,463.24,51.28,458.54,51.61,466.67,53.75,455.18,54.67,...,456.14,108.12,475.98,143.02,451.46,145.41,482.58,174.90,448.03,176.59
26466,461.09,53.89,463.25,51.28,458.53,51.61,466.69,53.75,455.19,54.67,...,456.12,108.15,475.99,143.01,451.49,145.39,482.64,174.85,448.03,176.58
26467,461.09,53.90,463.24,51.29,458.53,51.62,466.68,53.77,455.18,54.67,...,456.07,108.18,475.98,143.00,451.52,145.43,482.56,174.78,448.09,176.57
26468,461.10,53.89,463.24,51.28,458.52,51.62,466.69,53.76,455.17,54.65,...,456.00,108.30,475.98,142.99,451.52,145.50,482.58,174.70,448.12,176.54

In [14]:
df_full_body.to_csv('full_body.csv', index=False)
df_half_body.to_csv('half_body.csv', index=False)